### ISSUE TITLE
configurable plugin list

### ISSUE THREAD

**Issue by tilmanschweitzer** [tschaefer/upmctl#1]
It would be great to specify a file which contains a list of plugin keys. The output json should only contain plugins from the list

```
# as parameter with a comma separated list 
upmctl --base-url <url> --plugin-list=org.example.plugin.x,org.example.plugin.y
```

   # as config file - keys separated by comma or newline
   upmctl --base-url <url> --plugin-list-file=myplugins.conf

**Comment by tschaefer** [comment]
I created following options to limit / filter the listed plugins by a regular expression.

```
$ upmctl list -h
...
--key KEY             list plugins by regex key
--key-configuration-file KEY_CONFIGURATION_FILE
                             list plugins by regex key in configuration file
```

So it is possible to provide a list of plugin keys seperated by a pipe.

```
upmctl --base-url "http://acme.org" --base-authentication "foo:bar"  list \
--key "org.acme.plugin.x|org.acme.plugin.y"
```

Or shorter as regex pattern.

```
upmctl --base-url "http://acme.org" --base-authentication "foo:bar"  list \
--key "^org.acme.plugin.*$"
```

The key configuration file must provide a structure similar to what you would find on Microsoft Windows INI files.

```
[UPM]
key=^org.acme.plugin.*$
```

See code comparsion [last 24h](https://github.com/tschaefer/upmctl/compare/master@%7B1day%7D...master).
